// Generated by https://quicktype.io

declare global {
  interface StockResponse {
    rawData: RawData;
  }

  interface RawData {
    error: boolean;
    currency: string;
    response: Response[];
  }

  interface Response {
    date: number;
    open: number;
    high: number;
    low: number;
    close: number;
    volume: number;
    adjclose: number;
  }

  export interface StaticTickerData {
    Symbol: string;
    Name: string;
    Country: Country | string;
    "IPO Year": number | string;
    Sector: Sector | string;
    Industry: string;
  }

  export enum Country {
    Argentina = "Argentina",
    Australia = "Australia",
    Bahamas = "Bahamas",
    Belgium = "Belgium",
    Bermuda = "Bermuda",
    Brazil = "Brazil",
    Canada = "Canada",
    CaymanIslands = "Cayman Islands",
    Chile = "Chile",
    China = "China",
    Colombia = "Colombia",
    CostaRica = "Costa Rica",
    Curacao = "Curacao",
    Cyprus = "Cyprus",
    Denmark = "Denmark",
    Empty = "",
    Finland = "Finland",
    France = "France",
    Germany = "Germany",
    Gibraltar = "Gibraltar",
    Greece = "Greece",
    Guernsey = "Guernsey",
    HongKong = "Hong Kong",
    India = "India",
    Indonesia = "Indonesia",
    Ireland = "Ireland",
    IsleOfMan = "Isle of Man",
    Israel = "Israel",
    Italy = "Italy",
    Japan = "Japan",
    Jersey = "Jersey",
    Jordan = "Jordan",
    Kazakhstan = "Kazakhstan",
    Luxembourg = "Luxembourg",
    Macau = "Macau",
    Malaysia = "Malaysia",
    Malta = "Malta",
    Mexico = "Mexico",
    Monaco = "Monaco",
    Netherlands = "Netherlands",
    NewZealand = "New Zealand",
    Norway = "Norway",
    Panama = "Panama",
    Peru = "Peru",
    Philippines = "Philippines",
    PuertoRico = "Puerto Rico",
    Singapore = "Singapore",
    SouthAfrica = "South Africa",
    SouthKorea = "South Korea",
    Spain = "Spain",
    Sweden = "Sweden",
    Switzerland = "Switzerland",
    Taiwan = "Taiwan",
    Turkey = "Turkey",
    UnitedArabEmirates = "United Arab Emirates",
    UnitedKingdom = "United Kingdom",
    UnitedStates = "United States",
    Uruguay = "Uruguay",
  }

  export enum Sector {
    BasicMaterials = "Basic Materials",
    ConsumerDiscretionary = "Consumer Discretionary",
    ConsumerStaples = "Consumer Staples",
    Empty = "",
    Energy = "Energy",
    Finance = "Finance",
    HealthCare = "Health Care",
    Industrials = "Industrials",
    Miscellaneous = "Miscellaneous",
    RealEstate = "Real Estate",
    Technology = "Technology",
    Telecommunications = "Telecommunications",
    Utilities = "Utilities",
  }
}
export {};

// Generated by https://quicktype.io
