import type { NextPage } from "next";
import Head from "next/head";
import GlobeIcon from "../components/GlobeIcon";
import { WindowContainer } from "../components/WindowContainer";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const topBorderHeight = "h-[58px]";
  const windowHeight = "h-[800px]";
  const windowWidth = "w-[80vw]";

  return (
    <>
      <Head>
        <title>Will OS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5">
        <div className="flex h-[872px] w-[98vw] items-center justify-center border-[8px] border-black bg-[url('/ref.png')] bg-cover">
          {/* main contianer */}
          <WindowContainer
            topBorderHeight={topBorderHeight}
            windowHeight={windowHeight}
            windowWidth={windowWidth}
          >
            <div className="h-[734px] w-full bg-[url('/bTriangles.jpeg')] bg-cover">
              <div className="absolute top-[100px]">
                <WindowContainer
                  topBorderHeight="h-[30px]"
                  windowHeight="h-[400px]"
                  windowWidth="w-[700px]"
                >
                  <div className="graphPaper h-[362px] w-full"></div>
                </WindowContainer>
              </div>
            </div>
          </WindowContainer>
        </div>
      </main>
    </>
  );
};

export default Home;
