import type { NextPage } from "next";
import Head from "next/head";
import GlobeIcon from "../components/GlobeIcon";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Will OS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5">
        <div className="flex h-[872px] w-[98vw] items-center justify-center border-[8px] border-black bg-[url('/ref.png')] bg-cover">
          {/* main contianer */}
          <div className="relative z-10 ml-10 h-[800px] w-[80vw] bg-black">
            <div className="absolute right-5 bottom-3 z-30 h-[800px] w-[80vw] border-[4px]  border-black bg-white">
              <div className="flex h-[58px] w-[100%]  bg-black text-[24px] uppercase text-white">
                <div className="flex h-[100%] w-[10%] items-center justify-start  pl-2">
                  WILL.OS
                </div>
                <div className="flex h-[100%] w-[60%] items-center justify-start  ">
                  config 2022 *** Oct 15 *** 🥵 30 degrees
                </div>
                <div className="flex h-[100%] w-[30%] text-[16px]  ">
                  <div className="flex h-[100%] w-[50%] items-center justify-end pr-2 ">
                    10:00pm(GMT+2)
                  </div>
                  <div className="flex h-[100%]  w-[50%] items-center justify-items-start border-l-2 pl-5">
                    <GlobeIcon /> <div className="pl-5" /> DOH
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
